

kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  namespace: mysql

spec:
  clusterIP: None  #-> for headless service
  # this means it cant be accesed from outside

  selector:
    app: mysql
  ports:
  - port: 3306
    name: mysql
    targetPort: 3306

